name: GitHub Actions CI
on: [push]
jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: sh build.sh
      - name: Run tests
        run: sh unit-tests.sh
